refactor: Env clean ups, add openjd CLI command to job_dev README
* Update apply-conda-queue-env.py to remove trailing whitespace.
* Clean up conda queue environment samples.
    * Create virtual environments in directories with names randomized
      by `mktemp`.
    * Capture the environment activation by using `conda run` instead of
      `conda activate`. Deactivate by calling eval "$(conda shell.bash deactivate)".
      These changes let the environment work without `conda init`
      changes working in non-interactive contexts.
    * Use Python instead of bash $(()) expressions for math.
    * Add `--quiet` option to `conda create` and `conda install`
      commands, to remove incremental progress updates from the log.
    * Add a `conda list` call to the 'improved_caching' env enter when
      it is reusing an environment, so that it is easy to look at the
      contents of the virtual environment from each job's log view.
    * Fixed a failing case in the 'improved_caching' env exit, due to
      grep return exit code 1 when no cached environments exist.
* Update the job_dev_progression README to include specific instructions
  for both running the job on Deadline Cloud and running the job locally
  with the Open Job Description CLI.
* Update the job dev progression code to use `mkdir -p` so that repeated
  runs on the same workspace succeed.

Signed-off-by: Mark Wiebe <399551+mwiebe@users.noreply.github.com>
Signed-off-by: Michael Yuan <160265179+yuanmich2@users.noreply.github.com>

diff --git a/queue_environments/conda_queue_env_improved_caching.yaml b/queue_environments/conda_queue_env_improved_caching.yaml
--- a/queue_environments/conda_queue_env_improved_caching.yaml
+++ b/queue_environments/conda_queue_env_improved_caching.yaml
@@ -5,8 +5,8 @@ parameterDefinitions:
   type: STRING
   description: >
     This is a space-separated list of Conda package match specifications to
-    install for the job. E.g. "blender=3.6" for a job that renders frames in
-    Blender 3.6.
+    install for the job. E.g. "blender=4.3" for a job that renders frames in
+    Blender 4.3.
   default: ""
   userInterface:
     control: LINE_EDIT
@@ -116,6 +116,19 @@ environment:
         }
         trap 'conda_clean_on_error $?' EXIT
 
+        function remove_named_env {
+            for ENVS_DIR in $(conda info --json | python -c "import json, sys; v = json.load(sys.stdin); print('\n'.join(v['envs_dirs']))"); do
+                if [ -d $ENVS_DIR/$1 ]; then
+                    echo "Removing directory $ENVS_DIR/$1 for the environment"
+                    rm -rf $ENVS_DIR/$1
+                    if [ -d $ENVS_DIR/$1 ]; then
+                        echo "ERROR: Could not remove the directory. Possibly a permissions error or a process holding a lock."
+                        exit 1
+                    fi
+                fi
+            done
+        }
+
         NAMED_CONDA_ENV='{{Param.NamedCondaEnv}}'
 
         # If the special name 'AUTOMATIC' is provided, use the hash of the CondaChannels and CondaPackages
@@ -132,16 +145,7 @@ environment:
         # If we're not reusing the Conda env, clean up any prior ones
         if [ '{{Param.NamedCondaEnvAction}}' = 'REMOVE_AND_CREATE' ] && [ -n "$NAMED_CONDA_ENV" ]; then
             echo "NamedCondaEnvAction parameter is set to REMOVE_AND_CREATE, removing the virtual environment..."
-            for ENVS_DIR in $(conda info --json | python -c "import json, sys; v = json.load(sys.stdin); print('\n'.join(v['envs_dirs']))"); do
-                if [ -d $ENVS_DIR/$NAMED_CONDA_ENV ]; then
-                    echo "Removing directory $ENVS_DIR/$NAMED_CONDA_ENV for the environment"
-                    rm -rf $ENVS_DIR/$NAMED_CONDA_ENV
-                    if [ -d $ENVS_DIR/$NAMED_CONDA_ENV ]; then
-                        echo "ERROR: Could not remove the directory. Possibly a permissions error or a process holding a lock."
-                        exit 1
-                    fi
-                fi
-            done
+            remove_named_env "$NAMED_CONDA_ENV"
         fi
 
         # If requested, clean the Conda package cache
@@ -158,101 +162,85 @@ environment:
         # Initialize/activate the Conda virtual environment
         if [ -n "$NAMED_CONDA_ENV" ] && conda env list | grep -q "^$NAMED_CONDA_ENV "; then
             echo "Reusing the existing named Conda environment $NAMED_CONDA_ENV."
+            echo ""
 
-            # Activate the Conda environment
+            # Capture environment variables set by activation
             python '{{Env.File.OpenJDVarsStart}}' .vars
-            set +u
-            conda activate "$NAMED_CONDA_ENV"
-            set -u
-            python '{{Env.File.OpenJDVarsCapture}}' .vars
+            conda run -n "$NAMED_CONDA_ENV" python '{{Env.File.OpenJDVarsCapture}}' .vars
+            ENV_DIR=$(conda run -n "$NAMED_CONDA_ENV" bash -c 'echo $CONDA_PREFIX')
 
-            CURRENT_TIMESTAMP="$(date +%s)"
-            TIMESTAMP_FILE="$CONDA_PREFIX/var/log/conda_queue_env_update_timestamp"
+            CUR_TIMESTAMP="$(date +%s)"
+            TIMESTAMP_FILE="$ENV_DIR/var/log/conda_queue_env_update_timestamp"
+            UPDATE_AFTER='{{Param.NamedCondaEnvUpdateAfterMinutes}}'
             if [ -f "$TIMESTAMP_FILE" ]; then
-                PREVIOUS_UPDATE_TIMESTAMP="$(cat "$TIMESTAMP_FILE")"
-                MINUTES_SINCE_UPDATE="$(( ( $CURRENT_TIMESTAMP - $PREVIOUS_UPDATE_TIMESTAMP ) / 60 ))"
+                PREV_UPDATE_TIMESTAMP="$(cat "$TIMESTAMP_FILE")"
+                MINUTES_SINCE_UPDATE="$(python -c "print(($CUR_TIMESTAMP - $PREV_UPDATE_TIMESTAMP) // 60)")"
             else
                 echo "The file recording the previous timestamp was not found"
-                MINUTES_SINCE_UPDATE=0
+                MINUTES_SINCE_UPDATE="$UPDATE_AFTER"
             fi
             echo "Minutes elapsed since last update of this named Conda environment: $MINUTES_SINCE_UPDATE"
 
-            if [ $MINUTES_SINCE_UPDATE -ge {{Param.NamedCondaEnvUpdateAfterMinutes}} ]; then
-                echo "Elapsed time greater than or equal to {{Param.NamedCondaEnvUpdateAfterMinutes}} minutes, updating the environment packages to the latest"
-                set +u
-                conda install --yes \
-                    --update-all \
+            if [ $MINUTES_SINCE_UPDATE -ge $UPDATE_AFTER ]; then
+                echo "Elapsed time greater than or equal to $UPDATE_AFTER minutes, updating the environment packages to the latest"
+                conda install -n "$NAMED_CONDA_ENV" --yes --quiet \
                     $CONDA_PACKAGES \
                     $CHANNEL_OPTS
-                set -u
 
                 # Save the channels and packages used in the environment, to help out debugging
-                LOGFILE="$CONDA_PREFIX/var/log/conda_queue_env.log"
+                LOGFILE="$ENV_DIR/var/log/conda_queue_env.log"
                 echo "Updated $NAMED_CONDA_ENV env at $(date --iso-8601=minutes)" >> "$LOGFILE"
                 echo '  CondaChannels: {{Param.CondaChannels}}' >> "$LOGFILE"
                 echo '  CondaPackages: {{Param.CondaPackages}}' >> "$LOGFILE"
 
                 # Save a timestamp of when we updated
-                echo "$CURRENT_TIMESTAMP" > "$CONDA_PREFIX/var/log/conda_queue_env_update_timestamp"
+                echo "$CUR_TIMESTAMP" > "$ENV_DIR/var/log/conda_queue_env_update_timestamp"
             else
-                echo "Elapsed time less than {{Param.NamedCondaEnvUpdateAfterMinutes}} minutes, skipping updates"
+                echo "Elapsed time less than $UPDATE_AFTER minutes, skipping updates"
             fi
+
+            echo ""
+            conda list -n "$NAMED_CONDA_ENV"
         elif [ -n "$NAMED_CONDA_ENV" ]; then
             echo "Named Conda environment $NAMED_CONDA_ENV not found, creating it."
 
-            # Make sure there's no incomplete environment hanging around
-            for ENVS_DIR in $(conda info --json | python -c "import json, sys; v = json.load(sys.stdin); print('\n'.join(v['envs_dirs']))"); do
-                if [ -d $ENVS_DIR/$NAMED_CONDA_ENV ]; then
-                    echo "Removing directory $ENVS_DIR/$NAMED_CONDA_ENV for the environment"
-                    rm -rf $ENVS_DIR/$NAMED_CONDA_ENV
-                    if [ -d $ENVS_DIR/$NAMED_CONDA_ENV ]; then
-                        echo "ERROR: Could not remove the directory. Possibly a permissions error or a process holding a lock."
-                        exit 1
-                    fi
-                fi
-            done
+            # Remove incomplete environments
+            remove_named_env "$NAMED_CONDA_ENV"
 
-            # Create the virtual environment
-            conda create --yes \
+            conda create --yes --quiet \
                 --name "$NAMED_CONDA_ENV" \
                 $CONDA_PACKAGES \
                 $CHANNEL_OPTS
 
-            # Activate the Conda environment
+            # Capture environment variables set by activation
             python '{{Env.File.OpenJDVarsStart}}' .vars
-            set +u
-            conda activate "$NAMED_CONDA_ENV"
-            set -u
-            python '{{Env.File.OpenJDVarsCapture}}' .vars
+            conda run -n "$NAMED_CONDA_ENV" python '{{Env.File.OpenJDVarsCapture}}' .vars
+            ENV_DIR=$(conda run -n $NAMED_CONDA_ENV bash -c 'echo $CONDA_PREFIX')
 
-            # Save the channels and packages used in the environment, to help out debugging
-            LOGFILE="$CONDA_PREFIX/var/log/conda_queue_env.log"
+            # Save the channels and packages used in the environment, to help debugging
+            LOGFILE="$ENV_DIR/var/log/conda_queue_env.log"
             mkdir -p "$(dirname $LOGFILE)"
             echo "Created $NAMED_CONDA_ENV env at $(date --iso-8601=minutes)" >> "$LOGFILE"
             echo '  CondaChannels: {{Param.CondaChannels}}' >> "$LOGFILE"
             echo '  CondaPackages: {{Param.CondaPackages}}' >> "$LOGFILE"
 
             # Save a timestamp of when we updated
-            date +%s > "$CONDA_PREFIX/var/log/conda_queue_env_update_timestamp"
+            date +%s > "$ENV_DIR/var/log/conda_queue_env_update_timestamp"
         else
             echo "Creating temporary Conda environment in the session directory..."
 
-            # Create the virtual environment
-            conda create --yes \
-                -p '{{Session.WorkingDirectory}}/.env' \
+            ENV_DIR="$(mktemp -d '{{Session.WorkingDirectory}}/.env-XXXXX')"
+            conda create --yes --quiet \
+                -p "$ENV_DIR" \
                 $CONDA_PACKAGES \
                 $CHANNEL_OPTS
 
-            # Activate the Conda environment
+            # Capture environment variables set by activation
             python '{{Env.File.OpenJDVarsStart}}' .vars
-            set +u
-            conda activate '{{Session.WorkingDirectory}}/.env'
-            set -u
-            python '{{Env.File.OpenJDVarsCapture}}' .vars
+            conda run -p "$ENV_DIR" python '{{Env.File.OpenJDVarsCapture}}' .vars
         fi
 
-        # Print information about the environment
-        conda info
+        conda run -p "$ENV_DIR" conda info
     - name: Exit
       filename: conda-queue-env-exit.sh
       type: TEXT
@@ -264,34 +252,38 @@ environment:
         # after they haven't been used for 96 hours, a length of time chosen so that when a farm is idle
         # for a long weekend it doesn't clear all these environment caches.
 
+        # Deactivate the environment so we can delete it if necessary
+        set +u
+        eval "$(conda shell.bash deactivate)"
+        set -u
+
         ENV_DELETE_AFTER_HOURS=96
 
         echo "Cleaning up any automatically-named conda environments that weren't updated within $ENV_DELETE_AFTER_HOURS hours."
 
-        AUTO_CONDA_ENVS="$(conda env list | grep "^hashname_" | cut -d " " -f 1)"
+        AUTO_CONDA_ENVS="$(conda env list | { grep "^hashname_" || true; } | cut -d " " -f 1)"
         REMOVED_ENV=0
 
-        CURRENT_TIMESTAMP="$(date +%s)"
+        CUR_TIMESTAMP="$(date +%s)"
         for ENV_NAME in $AUTO_CONDA_ENVS; do
             echo "Checking environment $ENV_NAME"
+            ENV_DIR=$(conda run -n $ENV_NAME bash -c 'echo $CONDA_PREFIX')
 
-            set +u
-            conda activate $ENV_NAME
-            set -u
-
-            LOGFILE="$CONDA_PREFIX/var/log/conda_queue_env.log"
+            LOGFILE="$ENV_DIR/var/log/conda_queue_env.log"
             if [ -f "$LOGFILE" ]; then
                 # Creation and each update outputs 3 lines to the log, so print the last 3
                 tail -3 "$LOGFILE"
             fi
 
-            PREVIOUS_UPDATE_TIMESTAMP="$(cat "$CONDA_PREFIX/var/log/conda_queue_env_update_timestamp")"
-            HOURS_SINCE_UPDATE="$(( ( $CURRENT_TIMESTAMP - $PREVIOUS_UPDATE_TIMESTAMP ) / 1440 ))"
+            TIMESTAMP_FILE="$ENV_DIR/var/log/conda_queue_env_update_timestamp"
+            if [ -f "$TIMESTAMP_FILE" ]; then
+                PREV_UPDATE_TIMESTAMP="$(cat "$TIMESTAMP_FILE")"
+            else
+                echo "The file recording the previous timestamp was not found"
+                PREV_UPDATE_TIMESTAMP=0
+            fi
+            HOURS_SINCE_UPDATE="$(python -c print"(($CUR_TIMESTAMP - $PREV_UPDATE_TIMESTAMP) // 3600)")"
             echo "Environment was last updated $HOURS_SINCE_UPDATE hours ago."
-
-            set +u
-            conda deactivate
-            set -u
 
             if [ $HOURS_SINCE_UPDATE -gt $ENV_DELETE_AFTER_HOURS ]; then
                 echo "Elapsed time $HOURS_SINCE_UPDATE is greater than $ENV_DELETE_AFTER_HOURS hours, removing the environment."
@@ -303,8 +295,6 @@ environment:
         if [ "$REMOVED_ENV" = "1" ]; then
             echo "Cleaning the conda cache to reclaim disk space."
             conda clean --yes --all
-        else
-            echo "Nothing to clean up."
         fi
 
     - name: OpenJDVarsStart
